version: '2'
services:
  snssqs:
    image: localstack/localstack:0.13.3
    container_name: snssqs
    environment:
      SERVICES: "sns,sqs,sts"
      DEBUG: 1
    ports:
      - 127.0.0.1:4566:4566
